### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by xtsimpouris** [danielquinn/django-crocodile#1]
Due to urllib2, this is not working in python 3. Any plan to support this?

**Comment by danielquinn** [comment]
With the popularity of django-compressor, I've not bothered to keep this updated.  However, if you think there's something crocodile does that compressor doesn't, then I'd be happy to merge a pull request from you that updates this for Python 3.

**Comment by xtsimpouris** [comment]
Indeed, thanks for the quick response
